services:
  webserver:
    image: nginx:latest
    restart: always
    volumes:
      - ./public:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    build: .
    restart: always
    volumes:
      - ./public:/var/www/html
