networks:
  spectra:
    external: true

volumes:
  mariadb_volume:
  caddy_data:
  caddy_config:
  wikidocs_datasets:

services:
  caddy:
    image: caddy:2.8.4
    restart: unless-stopped
    env_file: .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./frontend/dist:/fe

  mariadb:
    image: mariadb:lts-ubi9
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: spectra
      MARIADB_ROOT_PASSWORD: password
    volumes: 
      - ./sqlScripts:/docker-entrypoint-initdb.d
      - mariadb_volume:/var/lib/mysql
    networks:
      spectra:
        ipv4_address: 172.20.0.50
      default:

  orchestrator:
    image: ghcr.io/vallemsec/spectra/orchestrator
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./orchestrator-config.yaml:/app/config.yaml
    networks:
      spectra:
      default:

  decody:
    image: ghcr.io/vallemsec/spectra/decody
    restart: unless-stopped
    env_file: .env
    environment:
      MARIADB_DATABASE: spectra
      MARIADB_HOST: mariadb
      MARIADB_PASSWORD: password
    volumes:
      - ./jsonSchemas:/schemas

  dockerrunner:
    image: ghcr.io/vallemsec/spectra/dockerrunner
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  wikidocs:
    image: zavy86/wikidocs
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - wikidocs_datasets:/datasets
