discovery_runners:
  - SUBFINDER
  - NMAP

always_run:

runners:  
  SUBFINDER:
    cmdargs:
      - "-duc"
      - "-silent"
      - "-d"
      - "{{req_domain}}"
    report: false
    container_name: subfinder
    image: projectdiscovery/subfinder
    image_version: latest
    parser_plugin: subfinder
    results:

  NMAP:
    cmdargs:
      - "-t"
      - "quick"
      - "{{[pass_results]}}"
    report: false
    container_name: nmap
    image: ghcr.io/vallemsec/spectra/portscanner
    image_version: latest
    parser_plugin: nmap
    results:
      80:
        - NUCLEI

  NUCLEI:
    cmdargs:
      - "{{req_domain}}"
    report: true
    container_name: nuclei
    image: spectra/nuclei
    image_version: local
    parser_plugin: Nuclei
    results:
