services:
  mariadb:
    image: mariadb:lts-ubi9
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: decody_devdb
    ports:
      - 3306:3306

  decody:
    build:
      context: .
    restart: unless-stopped
    environment:
      MARIADB_HOST: mariadb
    volumes:
      - ../jsonSchemas:/schemas
    ports:
      - "5001:5001"
