services:
    docker-runner:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "127.0.0.1:8008:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock