name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.x'

    - name: Build
      run: |
        find . -name 'go.mod' -execdir go build -v ./... \;


# Test all folders with Go code
    - name: Test
      run: |
        find . -name 'go.mod' -execdir go test ./... \;
